name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
          flutter-version: "3.10.6"

    - name: Restore packages
      run: flutter pub get

    - name: Build Android App Bundle
      run: flutter build apk --release -t lib/main_prd.dart

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
